# Generated by Django 6.0.4 on 2026-04-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='default_profile_pic.jpeg', upload_to=''),
        ),
    ]
